name: Deploy staging to s3
on:
  push:
    branches:
      - staging
jobs:
  build:
    name: Build files
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v3
        with: 
            node-version: 18
            cache: 'npm'
      - name: Build project files
        run: |
          npm ci
          npm run build
      - name: Deploy to s3
        env: 
            AWS_DEFAULT_REGION: us-east-1
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: 
          aws s3 cp dist s3://philagov-vue-apps/311-service-request-tracker/staging --recursive # change it